-- RETIRED: this file is intentionally non-executable.
--
-- The authoritative schema is the ordered chain in `supabase/migrations/`.
-- Applying a hand-maintained snapshot previously restored obsolete broad
-- grants for profiles, orders and Storage. Never deploy from this file.
--
-- Clean environment:
--   supabase db reset
--
-- Existing environment:
--   supabase migration list
--   supabase db push --dry-run
--   supabase db push
--
-- Generate a temporary review-only dump from a migrated database when a
-- snapshot is required. Do not commit it as an alternative deployment path.
