-- Visual product search using Marqo FashionSigLIP.
-- The 768 dimensions below were read from the loaded model output, not guessed.

create extension if not exists vector with schema extensions;

create table if not exists public.product_visual_embeddings (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  image_url text not null check (btrim(image_url) <> ''),
  image_hash text not null check (length(image_hash) = 64),
  embedding extensions.vector(768) not null,
  view_type text not null check (view_type in ('main', 'alternate')),
  model_version text not null check (btrim(model_version) <> ''),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, image_url, model_version)
);

create index if not exists product_visual_embeddings_product_idx
  on public.product_visual_embeddings (product_id);

create index if not exists product_visual_embeddings_model_idx
  on public.product_visual_embeddings (model_version);

create index if not exists product_visual_embeddings_hnsw_cosine_idx
  on public.product_visual_embeddings
  using hnsw (embedding extensions.vector_cosine_ops)
  with (m = 16, ef_construction = 96);

drop trigger if exists touch_product_visual_embeddings_updated_at
  on public.product_visual_embeddings;
create trigger touch_product_visual_embeddings_updated_at
before update on public.product_visual_embeddings
for each row execute function public.touch_listing_updated_at();

alter table public.product_visual_embeddings enable row level security;

-- Embeddings are an implementation detail. Mobile clients use FastAPI and
-- never read/write vectors or receive a service-role credential.
revoke all on table public.product_visual_embeddings from anon, authenticated;
grant all on table public.product_visual_embeddings to service_role;
grant usage, select on sequence public.product_visual_embeddings_id_seq to service_role;

create or replace function public.search_product_visual_candidates(
  p_query_embedding extensions.vector(768),
  p_model_version text,
  p_match_count integer default 200,
  p_category text default null,
  p_related_subcategories text[] default null,
  p_min_price numeric default null,
  p_max_price numeric default null,
  p_sizes text[] default null,
  p_brands text[] default null,
  p_conditions text[] default null,
  p_colors text[] default null
)
returns table (
  product_id uuid,
  image_url text,
  view_type text,
  visual_similarity double precision,
  title text,
  description text,
  price numeric,
  images text[],
  main_image text,
  category text,
  subcategory text,
  item_type text,
  brand text,
  size text,
  condition text,
  primary_color text,
  secondary_colors text[],
  gender text,
  published_at timestamptz,
  favorite_count bigint
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  with nearest as (
    select
      e.product_id,
      e.image_url,
      e.view_type,
      1 - (e.embedding <=> p_query_embedding) as visual_similarity
    from public.product_visual_embeddings e
    join public.products p on p.id = e.product_id
    where e.model_version = p_model_version
      and p.status = 'published'
      and coalesce(p.is_hidden, false) = false
      and (p_min_price is null or p.price >= p_min_price)
      and (p_max_price is null or p.price <= p_max_price)
      and (p_sizes is null or cardinality(p_sizes) = 0 or p.size = any(p_sizes))
      and (p_brands is null or cardinality(p_brands) = 0 or p.brand = any(p_brands))
      and (p_conditions is null or cardinality(p_conditions) = 0 or p.condition = any(p_conditions))
      and (
        p_colors is null or cardinality(p_colors) = 0
        or p.primary_color = any(p_colors)
        or p.secondary_colors && p_colors
      )
      and (
        p_category is null
        or p.category = p_category
        or (
          p_related_subcategories is not null
          and p.subcategory = any(p_related_subcategories)
        )
      )
    order by e.embedding <=> p_query_embedding
    limit least(greatest(coalesce(p_match_count, 200), 1), 300)
  )
  select
    n.product_id,
    n.image_url,
    n.view_type,
    n.visual_similarity,
    p.title,
    p.description,
    p.price,
    p.images,
    p.main_image,
    p.category,
    p.subcategory,
    p.item_type,
    p.brand,
    p.size,
    p.condition,
    p.primary_color,
    p.secondary_colors,
    p.gender,
    p.published_at,
    (select count(*) from public.product_favorites f where f.product_id = p.id::text) as favorite_count
  from nearest n
  join public.products p on p.id = n.product_id;
$$;

revoke all on function public.search_product_visual_candidates(
  extensions.vector, text, integer, text, text[], numeric, numeric,
  text[], text[], text[], text[]
) from public, anon, authenticated;
grant execute on function public.search_product_visual_candidates(
  extensions.vector, text, integer, text, text[], numeric, numeric,
  text[], text[], text[], text[]
) to service_role;

notify pgrst, 'reload schema';
